### ISSUE TITLE
No restarts after zypper exit code 106 ZYPPER_EXIT_INF_REPOS_SKIPPED

### ISSUE THREAD

**Issue by asvetter** [openSUSE/os-update#15]
If one of the repos is unavailable during zypper up, then zypper returns error 106 ZYPPER_EXIT_INF_REPOS_SKIPPED.
os-update then exits immediately before checks are made, if service-restart or reboot is needed.

I think in case of error 106 ZYPPER_EXIT_INF_REPOS_SKIPPED, this should be handled differently.

Two ways come to mind:
1. Ignore 106 like 103 and 102 in eval_zypper_retval() 
2. Handle 106 differently in eval_zypper_retval() , remember 106 in a variable (e.g. "returncode" ?) and return 106 instead of 0 in the end

What do you think?
I'll code it.

**Comment by thkukuk** [comment]
Return code 102 and 103 mean that the update itself was without errors, but that a reboot/restart is needed. We take care for it, so a retval of 0 is correct.
Return code 106 means, there was an error during update and the admin needs to look at it, so at the end, we should return 106, too, and not 0.

**Comment by asvetter** [comment]
Ok, after rethinking I did an exception for error 106. It does not exit in eval_zypper_retval(). Instead it goes on, checks for restarts and reboot and returns 106 at the end.

**Comment by asvetter** [comment]
Fixed in 1.12
