### ISSUE TITLE
Unify tabs and spaces

### ISSUE THREAD

**Issue by tacerus** [openSUSE/os-update#22]
Hi,

src/os-update.in seems to contain an inconsistent mix of tab characters and spaces for indentation of lines, making it tricky to integrate new features whilst adhering to a standard.
Do you prefer the tab or the spaces variant? I could then try to submit a reformatting to make it uniform.

Best,
Georg

**Comment by thkukuk** [comment]
I have no preference here, my editor handles that automatically correct.
